sudo: false
language: java
language: node_js
install:
      - ./mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - ./mvn clean install
before_install:
- npm install -g nsp
- npm install n
- sudo ./node_modules/.bin/n stable
- rm -rf ~/.nvm
cache:
  directories:
    - "node_modules"
    - ~/.npm

jobs:
  include:
    - stage: NPM audit
      script: npm run audit-ci
