language: java
language: node_js
install:
      - ./mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - ./mvn clean install
before_install:
- npm install n
- sudo ./node_modules/.bin/n stable
- rm -rf ~/.nvm
